name: OData Neo Build
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  build:
    runs-on: windows-2022
    steps:
    - name: Checking out code
      uses: actions/checkout@v2
    - name: Setting up DotNet version
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.100-preview.1.22110.4
        include-prerelease: true
    - name: Restoring Nuget Packages
      run: dotnet restore
    - name: Building Solution
      run: dotnet build --no-restore
    - name: Testing
      run: dotnet test --no-build --verbosity normal
